In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("sales_table.csv")

In [6]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0
5,1006,furniture,tables,corporate,9428.0,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,NaN,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.0,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.0,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.0,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.0,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.0,-178.0,18.0
12,1013,technology,phones,corporate,6425.0,1864.0,7.0
13,1014,furniture,tables,consumer,1250.0,2208.0,8.0
14,1015,technology,phones,consumer,4314.0,-87.0,13.0
15,1016,technology,phones,Consumer,6477.0,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.0,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.0,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.0,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.0,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.0,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.0,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.0,NaN,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.0,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.0,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.0,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.0,NaN,6.0
27,1028,furniture,tables,Consumer,NaN,NaN,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.0,529.0,18.0
29,1030,office supplies,binders,corporate,2376.0,2292.0,NaN
30,1031,technology,phones,corporate,6073.0,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.0,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.0,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0
35,1036,technology,phones,Consumer,819.0,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.0,486.0,19.0
37,1038,office supplies,binders,consumer,8462.0,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.0,2593.0,7.0
41,1042,furniture,tables,home office,7037.0,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,NaN,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.0,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,NaN
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [7]:
df.head()

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0

In [8]:
df.tail()

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,NaN
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [9]:
df.describe()

         Order ID        Sales       Profit   Quantity
count    50.00000    47.000000    47.000000  47.000000
mean   1025.50000  5351.063830  1139.744681  10.978723
std      14.57738  2962.622431  1145.804435   5.612445
min    1001.00000   819.000000  -498.000000   1.000000
25%    1013.25000  2684.500000   -23.500000   7.000000
50%    1025.50000  6014.000000  1143.000000  11.000000
75%    1037.75000  7726.000000  2229.500000  16.000000
max    1050.00000  9855.000000  2971.000000  20.000000

In [21]:
df.isnull().sum()

Order ID        0
Category        0
Sub-Category    0
Segment         0
Sales           0
Profit          0
Quantity        0
dtype: int64

In [22]:
df['Profit']=df['Profit'].ffill()

In [23]:
df['Sales']=df['Sales'].bfill()

In [24]:
df['Quantity']=df['Quantity'].ffill()

In [25]:
df.duplicated().sum()

np.int64(0)

In [31]:
df['Profit'].mean()
df['Profit'].median()
df['Profit'].mode()

0    1587.0
Name: Profit, dtype: float64

In [32]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,19.0
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0
5,1006,furniture,tables,corporate,9428.0,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,7424.0,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.0,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.0,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.0,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.0,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.0,-178.0,18.0
12,1013,technology,phones,corporate,6425.0,1864.0,7.0
13,1014,furniture,tables,consumer,1250.0,2208.0,8.0
14,1015,technology,phones,consumer,4314.0,-87.0,13.0
15,1016,technology,phones,Consumer,6477.0,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.0,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.0,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.0,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.0,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.0,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.0,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.0,2440.0,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.0,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.0,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.0,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.0,1587.0,6.0
27,1028,furniture,tables,Consumer,9169.0,1587.0,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.0,529.0,18.0
29,1030,office supplies,binders,corporate,2376.0,2292.0,18.0
30,1031,technology,phones,corporate,6073.0,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.0,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.0,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0
35,1036,technology,phones,Consumer,819.0,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.0,486.0,19.0
37,1038,office supplies,binders,consumer,8462.0,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.0,2593.0,7.0
41,1042,furniture,tables,home office,7037.0,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,6039.0,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.0,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,3.0
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [34]:
df['Sales'].mean()
df['Sales'].median()
df['Sales'].mode()

0    6039.0
1    7424.0
2    9169.0
Name: Sales, dtype: float64

In [35]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,19.0
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0
5,1006,furniture,tables,corporate,9428.0,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,7424.0,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.0,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.0,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.0,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.0,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.0,-178.0,18.0
12,1013,technology,phones,corporate,6425.0,1864.0,7.0
13,1014,furniture,tables,consumer,1250.0,2208.0,8.0
14,1015,technology,phones,consumer,4314.0,-87.0,13.0
15,1016,technology,phones,Consumer,6477.0,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.0,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.0,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.0,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.0,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.0,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.0,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.0,2440.0,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.0,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.0,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.0,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.0,1587.0,6.0
27,1028,furniture,tables,Consumer,9169.0,1587.0,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.0,529.0,18.0
29,1030,office supplies,binders,corporate,2376.0,2292.0,18.0
30,1031,technology,phones,corporate,6073.0,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.0,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.0,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0
35,1036,technology,phones,Consumer,819.0,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.0,486.0,19.0
37,1038,office supplies,binders,consumer,8462.0,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.0,2593.0,7.0
41,1042,furniture,tables,home office,7037.0,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,6039.0,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.0,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,3.0
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [36]:
df['Quantity'].mean()
df['Quantity'].median()
df['Quantity'].mode()

0     3.0
1    18.0
Name: Quantity, dtype: float64

In [37]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,19.0
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0
5,1006,furniture,tables,corporate,9428.0,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,7424.0,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.0,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.0,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.0,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.0,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.0,-178.0,18.0
12,1013,technology,phones,corporate,6425.0,1864.0,7.0
13,1014,furniture,tables,consumer,1250.0,2208.0,8.0
14,1015,technology,phones,consumer,4314.0,-87.0,13.0
15,1016,technology,phones,Consumer,6477.0,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.0,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.0,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.0,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.0,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.0,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.0,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.0,2440.0,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.0,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.0,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.0,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.0,1587.0,6.0
27,1028,furniture,tables,Consumer,9169.0,1587.0,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.0,529.0,18.0
29,1030,office supplies,binders,corporate,2376.0,2292.0,18.0
30,1031,technology,phones,corporate,6073.0,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.0,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.0,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0
35,1036,technology,phones,Consumer,819.0,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.0,486.0,19.0
37,1038,office supplies,binders,consumer,8462.0,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.0,2593.0,7.0
41,1042,furniture,tables,home office,7037.0,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,6039.0,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.0,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,3.0
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [38]:
df["Category"]=df["Category"].str.strip().str.title()

In [41]:
df["Sub_Category"]=df["Segment"].str.strip().str.title()

In [42]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity,Sub_Category
0,1001,Furniture,tables,consumer,909.0,2537.0,9.0,Consumer
1,1002,Furniture,CHAIRS,CORPORATE,2786.0,2516.0,4.0,Corporate
2,1003,Furniture,tables,corporate,9435.0,-144.0,19.0,Corporate
3,1004,Office Supplies,storage,consumer,988.0,-117.0,19.0,Consumer
4,1005,Furniture,CHAIRS,HOME OFFICE,934.0,1798.0,7.0,Home Office
5,1006,Furniture,tables,corporate,9428.0,1218.0,8.0,Corporate
6,1007,Office Supplies,storage,HOME OFFICE,7424.0,2815.0,1.0,Home Office
7,1008,Furniture,CHAIRS,corporate,7424.0,893.0,9.0,Corporate
8,1009,Furniture,CHAIRS,CORPORATE,6014.0,-82.0,3.0,Corporate
9,1010,Office Supplies,storage,consumer,6381.0,2971.0,12.0,Consumer
10,1011,Technology,ACCESSORIES,home office,1211.0,2488.0,15.0,Home Office
11,1012,Technology,ACCESSORIES,consumer,6701.0,-178.0,18.0,Consumer
12,1013,Technology,phones,corporate,6425.0,1864.0,7.0,Corporate
13,1014,Furniture,tables,consumer,1250.0,2208.0,8.0,Consumer
14,1015,Technology,phones,consumer,4314.0,-87.0,13.0,Consumer
15,1016,Technology,phones,Consumer,6477.0,166.0,12.0,Consumer
16,1017,Technology,phones,CORPORATE,4874.0,2374.0,3.0,Corporate
17,1018,Technology,ACCESSORIES,corporate,3303.0,1687.0,8.0,Corporate
18,1019,Furniture,CHAIRS,Consumer,6716.0,605.0,18.0,Consumer
19,1020,Furniture,CHAIRS,corporate,5813.0,2952.0,2.0,Corporate
20,1021,Furniture,CHAIRS,consumer,5668.0,1143.0,9.0,Consumer
21,1022,Office Supplies,binders,CORPORATE,9792.0,2440.0,11.0,Corporate
22,1023,Furniture,CHAIRS,corporate,8679.0,2440.0,15.0,Corporate
23,1024,Furniture,CHAIRS,home office,2787.0,510.0,18.0,Home Office
24,1025,Technology,ACCESSORIES,home office,7519.0,1890.0,13.0,Home Office
25,1026,Technology,phones,CORPORATE,2766.0,1587.0,16.0,Corporate
26,1027,Office Supplies,binders,consumer,2296.0,1587.0,6.0,Consumer
27,1028,Furniture,tables,Consumer,9169.0,1587.0,13.0,Consumer
28,1029,Technology,ACCESSORIES,Consumer,9169.0,529.0,18.0,Consumer
29,1030,Office Supplies,binders,corporate,2376.0,2292.0,18.0,Corporate
30,1031,Technology,phones,corporate,6073.0,-44.0,10.0,Corporate
31,1032,Office Supplies,storage,CORPORATE,7933.0,-487.0,9.0,Corporate
32,1033,Technology,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0,Corporate
33,1034,Furniture,tables,HOME OFFICE,3758.0,126.0,12.0,Home Office
34,1035,Furniture,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0,Home Office
35,1036,Technology,phones,Consumer,819.0,-42.0,12.0,Consumer
36,1037,Technology,phones,CORPORATE,1449.0,486.0,19.0,Corporate
37,1038,Office Supplies,binders,consumer,8462.0,2842.0,3.0,Consumer
38,1039,Technology,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0,Corporate
39,1040,Technology,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0,Corporate
40,1041,Office Supplies,storage,CORPORATE,9335.0,2593.0,7.0,Corporate
41,1042,Furniture,tables,home office,7037.0,2251.0,12.0,Home Office
42,1043,Office Supplies,storage,HOME OFFICE,6039.0,-5.0,8.0,Home Office
43,1044,Furniture,CHAIRS,consumer,6039.0,-414.0,19.0,Consumer
44,1045,Technology,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0,Corporate
45,1046,Furniture,tables,corporate,1464.0,437.0,3.0,Corporate
46,1047,Office Supplies,binders,home office,1660.0,1605.0,3.0,Home Office
47,1048,Technology,phones,corporate,8453.0,377.0,18.0,Corporate
48,1049,Furniture,CHAIRS,corporate,9855.0,1860.0,16.0,Corporate
49,1050,Furniture,CHAIRS,Consumer,7169.0,279.0,4.0,Consumer